### ISSUE TITLE
Configured to use the Rumba board?

### ISSUE THREAD

**Issue by kengdahl** [Sharebot3D/Materia101#5]
Why is this firmware configured to use the Rumba board in the configuration.h file? 

Did you work-around the configuration.h file?

**Comment by Sharebot3D** [comment]
Yes, I did. If you look at the beginning of Configuration.h there are the following lines:
...
#define CFG_MATERIA101

#ifdef CFG_MATERIA101
#undef CONFIGURATION_H
#include "cfg_materia101.h"
#include "cfg_materia101_adv.h"
...

For Materia101 the configuration files are called:
Configuration.h -> "cfg_materia101.h"
Configuration_adv.h -> "cfg_materia101_adv.h"

**Comment by kengdahl** [comment]
Thank you :+1:
